### ISSUE TITLE
我打包为微信小程序后，真机调试一直报这个错   我该如何处理？

### ISSUE THREAD

**Issue by pengboooo** [ahua666/tuniaoUI#12]
我打包为微信小程序后，真机调试一直报这个错   我该如何处理？
Cannot read property 'left' of null
TypeError: Cannot read property 'left' of null
    at eval (weapp:///tuniao-ui/components/tn-tabbar/tn-tabbar.js:183:27)
    at Array.map (<anonymous>)
    at Object.eval (weapp:///tuniao-ui/components/tn-tabbar/tn-tabbar.js:181:41)
    at Function.eval (eval at Ce.t.call.document (http://127.0.0.1:33006/remote-debug/runtime.js?devtools_ignore=true:1:18762), <anonymous>:2:1776758)
    at <SelectorQuery callback function>
    at eval (eval at Ce.t.call.document (http://127.0.0.1:33006/remote-debug/runtime.js?devtools_ignore=true:1:18762), <anonymous>:2:166058)
    at eval (eval at Ce.t.call.document (http://127.0.0.1:33006/remote-debug/runtime.js?devtools_ignore=true:1:18762), <anonymous>:2:1776884)
    at Array.forEach (<anonymous>)
    at eval (eval at Ce.t.call.document (http://127.0.0.1:33006/remote-debug/runtime.js?devtools_ignore=true:1:18762), <anonymous>:2:1776872)
    at eval (eval at Ce.t.call.document (http://127.0.0.1:33006/remote-debug/runtime.js?devtools_ignore=true:1:18762), <anonymous>:2:1773376)

**Comment by ahua666** [comment]
1
